CREATE TABLE ICON(
ID int  IDENTITY(1,1) PRIMARY KEY,
MEDIUM varchar(500) NULL
)

CREATE TABLE CARD(
ID int IDENTITY(1,1),
NAME varchar(100),
GAME_CARD_ID int,
MAXLEVEL int,
ICON_ID int,
PRIMARY KEY(ID,GAME_CARD_ID),
CONSTRAINT CARD_ICON_ICON_ID FOREIGN KEY (ICON_ID)  REFERENCES ICON(ID)
)

